name: fusion_swap_sdk
description: Utils library for 1inch Fusion Mode.
version: 1.0.3
homepage: https://wakumo.vn
repository: https://github.com/wakumo/fusion-sdk

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  dio: ^5.3.3
  eth_sig_util: 0.0.9
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  web3dart: 2.3.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.3.2
  json_serializable: ^6.6.2
  freezed: ^2.3.5
